version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy_config/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./media:/srv/media
      - ./media-2:/srv/media-2
      - ./frontend/dist:/srv/frontend
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: node_backend
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - CADDY_CONTAINER_NAME=caddy_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
