docRoot                          /srv/
enableGzip                       1

errorlog $SERVER_ROOT/logs/app.error.log {
  useServer                      0
  logLevel                       WARN
  rollingSize                    10M
}

accesslog $SERVER_ROOT/logs/app.access.log {
  useServer                      0
  rollingSize                    10M
  keepDays                       30
  compressArchive                0
  logReferer                     1
  logUserAgent                   1
}

accessControl {
  allow                          ALL
}

rewrite {
  enable                         1
  rules                          <<<END_rules
RewriteCond %{SERVER_PORT} 80
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
END_rules
}

extprocessor backend {
  type                           proxy
  address                        127.0.0.1:3000
  maxConns                       100
  initTimeout                    60
  retryTimeout                   0
  respBuffer                     0
  persistConn                    1
  pcKeepAliveTimeout             60
}

extprocessor frontend {
  type                           proxy
  address                        frontend:80
  maxConns                       100
  initTimeout                    60
  retryTimeout                   0
  respBuffer                     0
  persistConn                    1
  pcKeepAliveTimeout             60
}

context /video/ {
  type                           static
  location                       /srv/video/
  allowBrowse                    1
  addDefaultCharset              off
  extraHeaders                   <<<END_extraHeaders
Cache-Control no-store, no-cache, must-revalidate, max-age=0
Pragma no-cache
Expires 0
Timing-Allow-Origin *
Access-Control-Allow-Origin *
Access-Control-Allow-Methods GET, HEAD, OPTIONS
Access-Control-Allow-Headers Content-Type, Authorization, Range
END_extraHeaders
}

context /api/ {
  type                           proxy
  handler                        backend
  addDefaultCharset              off
}

context / {
  type                           proxy
  handler                        frontend
  addDefaultCharset              off
}

index {
  useServer                      0
  indexFiles                     index.html
  autoIndex                      0
}

vhssl {
  keyFile                        $SERVER_ROOT/conf/cert/server.key
  certFile                       $SERVER_ROOT/conf/cert/server.crt
  certChain                      1
  enableSpdy                     15
  enableQuic                     1
}
